pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-oag-sftp-docker
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - OAG_PVC_SIZE=5Gi
      - OAG_CPU_REQUEST=1
      - OAG_CPU_LIMIT=1.5
      - OAG_RAM_REQUEST=1Gi
      - OAG_RAM_LIMIT=1.5Gi
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - export SSH_REMOTE_HOST_MAYTECH=$$NOTPROD_SSH_REMOTE_HOST_MAYTECH
      - export SSH_REMOTE_USER_MAYTECH=$$NOTPROD_SSH_REMOTE_USER_MAYTECH
      - export SSH_PRIVATE_KEY=$$NOTPROD_SSH_PRIVATE_KEY
      - export SSH_LANDING_DIR=$$NOTPROD_SSH_LANDING_DIR
      - export S3_BUCKET_NAME=$$NOTPROD_S3_BUCKET_NAME
      - export S3_KEY_PREFIX=$$NOTPROD_S3_KEY_PREFIX
      - export S3_ACCESS_KEY_ID=$$NOTPROD_S3_ACCESS_KEY_ID
      - export S3_SECRET_ACCESS_KEY=$$NOTPROD_S3_SECRET_ACCESS_KEY
      - kd -f kube/pvc.yml -f kube/secret.yml -f kube/service.yml -f kube/deployment.yml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
      - NOTPROD_SSH_REMOTE_HOST_MAYTECH
      - NOTPROD_SSH_REMOTE_USER_MAYTECH
      - NOTPROD_SSH_PRIVATE_KEY
      - NOTPROD_SSH_LANDING_DIR
      - NOTPROD_S3_BUCKET_NAME
      - NOTPROD_S3_KEY_PREFIX
      - NOTPROD_S3_ACCESS_KEY_ID
      - NOTPROD_S3_SECRET_ACCESS_KEY
    when:
      event: push
