pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-oag-sftp-docker
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - OAG_PVC_SIZE=1Gi
      - OAG_CPU_REQUEST=1
      - OAG_CPU_LIMIT=1.5
      - OAG_RAM_REQUEST=1Gi
      - OAG_RAM_LIMIT=1.5Gi
      - CLAMAV_CPU_REQUEST=1
      - CLAMAV_CPU_LIMIT=1.5
      - CLAMAV_RAM_REQUEST=1Gi
      - CLAMAV_RAM_LIMIT=1.5Gi
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - export SSH_REMOTE_HOST_MAYTECH=$$NOTPROD_SSH_REMOTE_HOST_MAYTECH
      - export SSH_REMOTE_USER_MAYTECH=$$NOTPROD_SSH_REMOTE_USER_MAYTECH
      - export SSH_PRIVATE_KEY=$$NOTPROD_SSH_PRIVATE_KEY_PATH
      - export PRIVATE_KEY=$$NOTPROD_SSH_PRIVATE_KEY
      - export SSH_LANDING_DIR=$$NOTPROD_SSH_LANDING_DIR
      - export S3_BUCKET_NAME=$$NOTPROD_S3_BUCKET_NAME
      - export S3_ACCESS_KEY_ID=$$NOTPROD_S3_ACCESS_KEY_ID
      - export S3_SECRET_ACCESS_KEY=$$NOTPROD_S3_SECRET_ACCESS_KEY
      - export OAG_RDS_HOST=$$NOTPROD_OAG_RDS_HOST
      - export OAG_RDS_DATABASE=$$NOTPROD_OAG_RDS_DATABASE
      - export OAG_RDS_USERNAME=$$NOTPROD_OAG_RDS_USERNAME
      - export OAG_RDS_PASSWORD=$$NOTPROD_OAG_RDS_PASSWORD
      - export OAG_RDS_TABLE=$$NOTPROD_OAG_RDS_TABLE
      - export SLACK_WEBHOOK=$$NOTPROD_SLACK_WEBHOOK
      - kd -f kube/pvc.yml -f kube/secret.yml -f kube/deployment.yml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
      - NOTPROD_SSH_REMOTE_HOST_MAYTECH
      - NOTPROD_SSH_REMOTE_USER_MAYTECH
      - NOTPROD_SSH_PRIVATE_KEY
      - NOTPROD_SSH_PRIVATE_KEY_PATH
      - NOTPROD_SSH_LANDING_DIR
      - NOTPROD_S3_BUCKET_NAME
      - NOTPROD_S3_ACCESS_KEY_ID
      - NOTPROD_S3_SECRET_ACCESS_KEY
      - NOTPROD_OAG_RDS_HOST
      - NOTPROD_OAG_RDS_DATABASE
      - NOTPROD_OAG_RDS_USERNAME
      - NOTPROD_OAG_RDS_PASSWORD
      - NOTPROD_OAG_RDS_TABLE
      - NOTPROD_SLACK_WEBHOOK
    when:
      event: push

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps
      - INSECURE_SKIP_TLS_VERIFY=true
      - OAG_PVC_SIZE=5Gi
      - OAG_CPU_REQUEST=2
      - OAG_CPU_LIMIT=2.5
      - OAG_RAM_REQUEST=3Gi
      - OAG_RAM_LIMIT=4Gi
      - CLAMAV_CPU_REQUEST=2
      - CLAMAV_CPU_LIMIT=2.5
      - CLAMAV_RAM_REQUEST=3Gi
      - CLAMAV_RAM_LIMIT=4Gi
    commands:
      - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
      - export KUBE_SERVER=$$PROD_KUBE_SERVER
      - export SSH_REMOTE_HOST_MAYTECH=$$PROD_SSH_REMOTE_HOST_MAYTECH
      - export SSH_REMOTE_USER_MAYTECH=$$PROD_SSH_REMOTE_USER_MAYTECH
      - export SSH_PRIVATE_KEY=$$PROD_SSH_PRIVATE_KEY_PATH
      - export PRIVATE_KEY=$$PROD_SSH_PRIVATE_KEY
      - export SSH_LANDING_DIR=$$PROD_SSH_LANDING_DIR
      - export S3_BUCKET_NAME=$$PROD_S3_BUCKET_NAME
      - export S3_ACCESS_KEY_ID=$$PROD_S3_ACCESS_KEY_ID
      - export S3_SECRET_ACCESS_KEY=$$PROD_S3_SECRET_ACCESS_KEY
      - export OAG_RDS_HOST=$$PROD_OAG_RDS_HOST
      - export OAG_RDS_DATABASE=$$PROD_OAG_RDS_DATABASE
      - export OAG_RDS_USERNAME=$$PROD_OAG_RDS_USERNAME
      - export OAG_RDS_PASSWORD=$$PROD_OAG_RDS_PASSWORD
      - export OAG_RDS_TABLE=$$PROD_OAG_RDS_TABLE
      - export SLACK_WEBHOOK=$$PROD_SLACK_WEBHOOK
      - kd -f kube/pvc.yml -f kube/secret.yml -f kube/deployment.yml
    secrets:
      - PROD_KUBE_TOKEN
      - PROD_KUBE_SERVER
      - PROD_SSH_REMOTE_HOST_MAYTECH
      - PROD_SSH_REMOTE_USER_MAYTECH
      - PROD_SSH_PRIVATE_KEY
      - PROD_SSH_PRIVATE_KEY_PATH
      - PROD_SSH_LANDING_DIR
      - PROD_S3_BUCKET_NAME
      - PROD_S3_ACCESS_KEY_ID
      - PROD_S3_SECRET_ACCESS_KEY
      - PROD_OAG_RDS_HOST
      - PROD_OAG_RDS_DATABASE
      - PROD_OAG_RDS_USERNAME
      - PROD_OAG_RDS_PASSWORD
      - PROD_OAG_RDS_TABLE
      - PROD_SLACK_WEBHOOK
    when:
      environment: production
      branch: master
      event: deployment
